function [ s ] = IMSPE_integrals( x,y, theta,p,cov_type,TENSORISED)
% function [ s ] = IMSPE_integrals( x,y, theta,p,cov_type,TENSORISED)
%-------------------
% For dimension d>1, REQUIRES TENSORISED = 1,
%   only for cov_type = 'Matern12', 'Matern32', 'Matern52', or 'Gaussian'  
%-------------------
% For K a kernel defined by cov_type (e.g., 'Matern32'), 
% with correlation length 1/theta (the additional parameter p is not used),
% computes s(x,y)=int_[0,1]^d K(x,t)K(y,t) dt
% for x (d*n) and y (d*1), which must have their components in [0,1], 
% returns s which is 1*n
%-----
% L. Pronzato, 2025
% Permission is granted to use, modify and redistribute this software for 
% non-commercial research and educational purposes only. Commercial use 
% requires prior written permission from the author.
%-----

[d,n]=size(x);
s=ones(1,n);

if d>1 && TENSORISED==0
    s=zeros(1,n);
    display('Error: K must be a tensorised kernel')
    return
end
if TENSORISED==1 
    for i=1:d
        [ si ] = IMSPE_integrals( x(i,:),y(i,:), theta,p,cov_type,0);
        s=s.*si;
    end
else
    switch lower(cov_type)
        case 'gaussian' 
            s = sqrt(pi)*exp(-theta*(x-y).^2/2)*sqrt(2)...
            .*( erf(sqrt(theta)*x*sqrt(2)/2+sqrt(2)*sqrt(theta)*y/2)...
            -erf(-sqrt(2)*sqrt(theta)+sqrt(theta)*x*sqrt(2)/2+sqrt(2)*sqrt(theta)*y/2) )...
            /sqrt(theta)/4;
        case 'matern12' % Formulae valid for y<z
            ixsmall=find(x<y);
            if isempty(ixsmall)==0
                z=x(ixsmall);
                  s(ixsmall) = -(exp(-theta*(z+y))-2*exp(theta*(z-y))+2*exp(theta*(z-y))*...
                      theta.*z-2*y*exp(theta*(z-y))*theta+exp(theta*(-2+z+y)))/theta/2;
            end
            ixbig=find(x>=y);
            if isempty(ixbig)==0
                z=y;
                y=x(ixbig);
                  s(ixbig) = -(exp(-theta*(z+y))-2*exp(theta*(z-y))+2*exp(theta*(z-y))*...
                      theta*z-2*y.*exp(theta*(z-y))*theta+exp(theta*(-2+z+y)))/theta/2;
            end            
        case 'matern32' % Formulae valid for y<z
            T=theta*sqrt(3);
            ixsmall=find(x<y);
            if isempty(ixsmall)==0
                z=x(ixsmall);
                  s1 = -1/12;
                  s4 = 6*exp(-T*(y+z))*T^2.*z*y+6*exp(T*(-2+y+z))*...
                      T^2.*z*y+24*exp((z-y)*T)*T^2.*z*y+30*exp((z-y)*T)*...
                      T.*z-30*exp((z-y)*T)*T*y+9*exp(-T*(y+z))*T.*z+...
                      9*exp(-T*(y+z))*T*y-9*exp(T*(-2+y+z))*T*y-...
                      9*exp(T*(-2+y+z))*T.*z-6*exp(T*(-2+y+z))*T^2*y-...
                      6*exp(T*(-2+y+z))*T^2.*z;
                  s3 = s4-2*exp((z-y)*T)*T^3*y^3-12*exp((z-y)*T)*...
                      T^2*y^2+2*exp((z-y)*T)*T^3.*z.^3-12*exp((z-y)*T)*...
                      T^2.*z.^2+6*exp(T*(-2+y+z))*T^2+18*exp(T*(-2+y+z))*...
                      T+6*exp((z-y)*T)*T^3.*z*y^2-6*exp((z-y)*T)*...
                      T^3.*z.^2*y-30*exp((z-y)*T)+15*exp(T*(-2+y+z))+...
                          15*exp(-T*(y+z));
                  s4 = 1/T;
                  s2 = s3*s4;
                  s(ixsmall) = s1*s2;                
            end
            ixbig=find(x>=y);
            if isempty(ixbig)==0
                z=y;
                y=x(ixbig);
                  s1 = -1/12;
                  s4 = 6*exp(-T*(y+z))*T^2*z.*y+6*exp(T*(-2+y+z))*...
                      T^2*z.*y+24*exp((z-y)*T)*T^2*z.*y+30*exp((z-y)*T)*...
                      T*z-30*exp((z-y)*T)*T.*y+9*exp(-T*(y+z))*T*z+...
                      9*exp(-T*(y+z))*T.*y-9*exp(T*(-2+y+z))*T.*y-...
                      9*exp(T*(-2+y+z))*T*z-6*exp(T*(-2+y+z))*T^2.*y-...
                      6*exp(T*(-2+y+z))*T^2*z;
                  s3 = s4-2*exp((z-y)*T)*T^3.*y.^3-12*exp((z-y)*T)*...
                      T^2.*y.^2+2*exp((z-y)*T)*T^3*z^3-12*exp((z-y)*T)*...
                      T^2*z^2+6*exp(T*(-2+y+z))*T^2+18*exp(T*(-2+y+z))*...
                      T+6*exp((z-y)*T)*T^3*z.*y.^2-6*exp((z-y)*T)*...
                      T^3*z^2.*y-30*exp((z-y)*T)+15*exp(T*(-2+y+z))+...
                          15*exp(-T*(y+z));
                  s4 = 1/T;
                  s2 = s3*s4;
                  s(ixbig) = s1*s2;  
            end
        case 'matern52' % Formulae valid for y<z --- from Maple Integrals_KK.mw
            T=theta*sqrt(5);
            ixsmall=find(x<y);
            if isempty(ixsmall)==0
                z=x(ixsmall);
                  s(ixsmall) = -(-0.30e2 * exp((-y + z) * T) * T ^ 4 .* z .^ 4 - 0.210e3 * exp((-y + z) * T) * T ^ 3 * y ^ 3 - ...
                      0.840e3 * exp((-y + z) * T) * T ^ 2 * y ^ 2 - 0.2e1 * exp((-y + z) * T) * T ^ 5 * y ^ 5 - ...
                      0.1890e4 * exp((-y + z) * T) * T * y + 0.2e1 * exp((-y + z) * T) * T ^ 5 .* z .^ 5 + ...
                      0.675e3 * exp(-(z + y) * T) .* z * T + 0.150e3 * exp(-(z + y) * T) * T ^ 2 .* z .^ 2 + ...
                      0.675e3 * exp(-(z + y) * T) * y * T + 0.210e3 * exp((-y + z) * T) * T ^ 3 .* z .^ 3 - ...
                      0.30e2 * exp((-y + z) * T) * T ^ 4 * y ^ 4 + 0.120e3 * exp(T * (z + y - 0.2e1)) .* z .^ 2 * T ^ 3 - ...
                      0.360e3 * exp(T * (z + y - 0.2e1)) .* z * T ^ 3 - 0.360e3 * exp(T * (z + y - 0.2e1)) * y * T ^ 3 - ...
                      0.810e3 * exp(T * (z + y - 0.2e1)) .* z * T ^ 2 - 0.810e3 * exp(T * (z + y - 0.2e1)) * y * T ^ 2 + ...
                      0.30e2 * exp(T * (z + y - 0.2e1)) .* z .^ 2 * T ^ 4 - 0.60e2 * exp(T * (z + y - 0.2e1)) .* z * T ^ 4 - ...
                      0.60e2 * exp(T * (z + y - 0.2e1)) * y * T ^ 4 + 0.30e2 * exp(T * (z + y - 0.2e1)) * y ^ 2 * T ^ 4 + ...
                      0.150e3 * exp(T * (z + y - 0.2e1)) .* z .^ 2 * T ^ 2 - 0.675e3 * exp(T * (z + y - 0.2e1)) * y * T - ...
                      0.675e3 * exp(T * (z + y - 0.2e1)) .* z * T + 0.120e3 * exp(T * (z + y - 0.2e1)) * y ^ 2 * T ^ 3 + ...
                      0.150e3 * exp(T * (z + y - 0.2e1)) * y ^ 2 * T ^ 2 + 0.1350e4 * exp(T * (z + y - 0.2e1)) * T + ...
                      0.240e3 * exp(T * (z + y - 0.2e1)) * T ^ 3 + 0.810e3 * exp(T * (z + y - 0.2e1)) * T ^ 2 + ...
                      0.30e2 * exp(T * (z + y - 0.2e1)) * T ^ 4 - 0.840e3 * exp((-y + z) * T) * T ^ 2 .* z .^ 2 - ...
                      0.1890e4 * exp((-y + z) * T) + 0.945e3 * exp(-(z + y) * T) + 0.945e3 * exp(T * (z + y - 0.2e1)) + ...
                      0.30e2 * exp(T * (z + y - 0.2e1)) * y ^ 2 .* z .^ 2 * T ^ 4 + 0.150e3 * exp(-(z + y) * T) * T ^ 2 * y ^ 2 + ...
                      0.120e3 * exp(T * (z + y - 0.2e1)) * y .* z * T ^ 4 + 0.510e3 * exp(T * (z + y - 0.2e1)) * y .* z * ...
                      T ^ 2 + 0.480e3 * exp(T * (z + y - 0.2e1)) * y .* z * T ^ 3 - 0.120e3 * exp(T * (z + y - 0.2e1)) .* z .^ 2 * y * T ^ 3 - ...
                      0.120e3 * exp(T * (z + y - 0.2e1)) * y ^ 2 .* z * T ^ 3 + 0.20e2 * exp((-y + z) * T) * T ^ 5 .* z .^ 3 * y ^ 2 - ...
                      0.180e3 * exp((-y + z) * T) * T ^ 4 .* z .^ 2 * y ^ 2 + 0.120e3 * exp((-y + z) * T) * T ^ 4 .* z .^ 3 * y - ...
                      0.10e2 * exp((-y + z) * T) * T ^ 5 .* z .^ 4 * y + 0.630e3 * exp((-y + z) * T) * T ^ 3 .* z * y ^ 2 + ...
                      0.1680e4 * exp((-y + z) * T) * T ^ 2 .* z * y - 0.630e3 * exp((-y + z) * T) * T ^ 3 .* z .^ 2 * y - ...
                      0.20e2 * exp((-y + z) * T) * T ^ 5 .* z .^ 2 * y ^ 3 + 0.120e3 * exp((-y + z) * T) * T ^ 4 * y ^ 3 .* z + ...
                      0.10e2 * exp((-y + z) * T) * T ^ 5 * y ^ 4 .* z + 0.30e2 * exp(-(z + y) * T) * y ^ 2 .* z .^ 2 * T ^ 4 + ...
                      0.120e3 * exp(-(z + y) * T) .* z .^ 2 * y * T ^ 3 + 0.510e3 * exp(-(z + y) * T) * y .* z * T ^ 2 + ...
                      0.120e3 * exp(-(z + y) * T) .* z * y ^ 2 * T ^ 3 - 0.60e2 * exp(T * (z + y - 0.2e1)) .* z .^ 2 * y * T ^ 4 - ...
                      0.60e2 * exp(T * (z + y - 0.2e1)) * y ^ 2 .* z * T ^ 4 + 0.1890e4 * exp((-y + z) * T) * T .* z) / T / 0.540e3;
            end
            ixbig=find(x>=y);
            if isempty(ixbig)==0
                z=y;
                y=x(ixbig);
                  s(ixbig) = -(-0.30e2 * exp((-y + z) * T) * T ^ 4 * z ^ 4 - 0.210e3 * exp((-y + z) * T) * T ^ 3 .* y .^ 3 - ...
                      0.840e3 * exp((-y + z) * T) * T ^ 2 .* y .^ 2 - 0.2e1 * exp((-y + z) * T) * T ^ 5 .* y .^ 5 - ...
                      0.1890e4 * exp((-y + z) * T) * T .* y + 0.2e1 * exp((-y + z) * T) * T ^ 5 * z ^ 5 + ...
                      0.675e3 * exp(-(z + y) * T) * z * T + 0.150e3 * exp(-(z + y) * T) * T ^ 2 * z ^ 2 + ...
                      0.675e3 * exp(-(z + y) * T) .* y * T + 0.210e3 * exp((-y + z) * T) * T ^ 3 * z ^ 3 - ...
                      0.30e2 * exp((-y + z) * T) * T ^ 4 .* y .^ 4 + 0.120e3 * exp(T * (z + y - 0.2e1)) * z ^ 2 * T ^ 3 - ...
                      0.360e3 * exp(T * (z + y - 0.2e1)) * z * T ^ 3 - 0.360e3 * exp(T * (z + y - 0.2e1)) .* y * T ^ 3 - ...
                      0.810e3 * exp(T * (z + y - 0.2e1)) * z * T ^ 2 - 0.810e3 * exp(T * (z + y - 0.2e1)) .* y * T ^ 2 + ...
                      0.30e2 * exp(T * (z + y - 0.2e1)) * z ^ 2 * T ^ 4 - 0.60e2 * exp(T * (z + y - 0.2e1)) * z * T ^ 4 - ...
                      0.60e2 * exp(T * (z + y - 0.2e1)) .* y * T ^ 4 + 0.30e2 * exp(T * (z + y - 0.2e1)) .* y .^ 2 * T ^ 4 + ...
                      0.150e3 * exp(T * (z + y - 0.2e1)) * z ^ 2 * T ^ 2 - 0.675e3 * exp(T * (z + y - 0.2e1)) .* y * T - ...
                      0.675e3 * exp(T * (z + y - 0.2e1)) * z * T + 0.120e3 * exp(T * (z + y - 0.2e1)) .* y .^ 2 * T ^ 3 + ...
                      0.150e3 * exp(T * (z + y - 0.2e1)) .* y .^ 2 * T ^ 2 + 0.1350e4 * exp(T * (z + y - 0.2e1)) * T + ...
                      0.240e3 * exp(T * (z + y - 0.2e1)) * T ^ 3 + 0.810e3 * exp(T * (z + y - 0.2e1)) * T ^ 2 + ...
                      0.30e2 * exp(T * (z + y - 0.2e1)) * T ^ 4 - 0.840e3 * exp((-y + z) * T) * T ^ 2 * z ^ 2 - ...
                      0.1890e4 * exp((-y + z) * T) + 0.945e3 * exp(-(z + y) * T) + 0.945e3 * exp(T * (z + y - 0.2e1)) + ...
                      0.30e2 * exp(T * (z + y - 0.2e1)) .* y .^ 2 * z ^ 2 * T ^ 4 + 0.150e3 * exp(-(z + y) * T) * T ^ 2 .* y .^ 2 + ...
                      0.120e3 * exp(T * (z + y - 0.2e1)) .* y * z * T ^ 4 + 0.510e3 * exp(T * (z + y - 0.2e1)) .* y * z * ...
                      T ^ 2 + 0.480e3 * exp(T * (z + y - 0.2e1)) .* y * z * T ^ 3 - 0.120e3 * exp(T * (z + y - 0.2e1)) * z ^ 2 .* y * T ^ 3 - ...
                      0.120e3 * exp(T * (z + y - 0.2e1)) .* y .^ 2 .* z * T ^ 3 + 0.20e2 * exp((-y + z) * T) * T ^ 5 * z ^ 3 .* y .^ 2 - ...
                      0.180e3 * exp((-y + z) * T) * T ^ 4 * z ^ 2 .* y .^ 2 + 0.120e3 * exp((-y + z) * T) * T ^ 4 * z ^ 3 .* y - ...
                      0.10e2 * exp((-y + z) * T) * T ^ 5 * z ^ 4 .* y + 0.630e3 * exp((-y + z) * T) * T ^ 3 * z .* y .^ 2 + ...
                      0.1680e4 * exp((-y + z) * T) * T ^ 2 * z .* y - 0.630e3 * exp((-y + z) * T) * T ^ 3 * z ^ 2 .* y - ...
                      0.20e2 * exp((-y + z) * T) * T ^ 5 * z ^ 2 .* y .^ 3 + 0.120e3 * exp((-y + z) * T) * T ^ 4 .* y .^ 3 .* z + ...
                      0.10e2 * exp((-y + z) * T) * T ^ 5 .* y .^ 4 * z + 0.30e2 * exp(-(z + y) * T) .* y .^ 2 * z ^ 2 * T ^ 4 + ...
                      0.120e3 * exp(-(z + y) * T) * z ^ 2 .* y * T ^ 3 + 0.510e3 * exp(-(z + y) * T) .* y * z * T ^ 2 + ...
                      0.120e3 * exp(-(z + y) * T) * z .* y .^ 2 * T ^ 3 - 0.60e2 * exp(T * (z + y - 0.2e1)) * z ^ 2 .* y * T ^ 4 - ...
                      0.60e2 * exp(T * (z + y - 0.2e1)) .* y .^ 2 * z * T ^ 4 + 0.1890e4 * exp((-y + z) * T) * T * z) / T / 0.540e3;  
            end
    end    
end    
end

